##PYTHON FUNDAMENTALS

In [1]:
print("hello world")

hello world


In [2]:
!nvidia-smi

Sat Sep 16 04:32:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [4]:
#scalar

scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX=torch.tensor([[7,7],
                     [7,7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([7, 7])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR=torch.tensor([[[2,3,4],
                      [5,6,7],
                      [5,64,4]]])
TENSOR

tensor([[[ 2,  3,  4],
         [ 5,  6,  7],
         [ 5, 64,  4]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
#create a random tensor with a size
random_tensor=torch.rand(2,10,4)
random_tensor

tensor([[[0.9346, 0.8888, 0.8151, 0.0977],
         [0.8041, 0.1924, 0.2355, 0.1765],
         [0.9215, 0.8160, 0.2083, 0.3781],
         [0.9235, 0.6609, 0.9374, 0.7323],
         [0.5177, 0.5350, 0.8322, 0.1708],
         [0.7613, 0.9353, 0.6069, 0.5563],
         [0.0634, 0.2587, 0.7616, 0.1731],
         [0.2712, 0.4490, 0.6239, 0.6702],
         [0.6639, 0.0561, 0.6358, 0.5774],
         [0.3470, 0.7819, 0.8796, 0.3554]],

        [[0.6331, 0.7518, 0.0936, 0.9684],
         [0.9740, 0.3304, 0.9287, 0.8935],
         [0.4207, 0.9077, 0.9689, 0.6957],
         [0.5429, 0.9339, 0.8889, 0.8550],
         [0.0272, 0.8690, 0.3782, 0.3671],
         [0.8323, 0.2230, 0.0803, 0.8875],
         [0.4391, 0.0421, 0.0264, 0.2986],
         [0.9475, 0.8689, 0.6243, 0.9062],
         [0.8435, 0.4073, 0.4793, 0.5228],
         [0.4850, 0.6173, 0.4306, 0.0556]]])

In [18]:
random_tensor.ndim

3

In [19]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,color channels
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
#create a tensor with zeros
zeros=torch.zeros(size=(2,10,4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
#create tensor of ones
ones=torch.ones(size=(2,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
#creating a tensor with range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
range=torch.arange(start=0,end=1000,step=100)
range

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [26]:
#creating tensors like
range_like=torch.zeros_like(input=range)
range_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#TENSOR DATATYPES


In [27]:
#float 32 tensor
float_32_tensor=torch.tensor([3.0,2.3,3.0],
                             dtype=None, #what datatype the tensor is
                             device=None, #what device is your tensor on
                             requires_grad=False) #wheter or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
int_32_tensor=torch.tensor([1,2,3], dtype= torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
float_16_tensor*int_32_tensor

tensor([3.0000, 4.6016, 9.0000], dtype=torch.float16)

In [31]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3713, 0.0199, 0.0073, 0.8370],
        [0.4195, 0.8870, 0.0853, 0.7550],
        [0.2508, 0.7506, 0.6367, 0.8697]])

In [32]:
print(some_tensor)
print(f"datatype of the tensor: {some_tensor.dtype}")
print(f"shape of the tensor: { some_tensor.shape}")
print(f"device of the tensor: { some_tensor.device}")


tensor([[0.3713, 0.0199, 0.0073, 0.8370],
        [0.4195, 0.8870, 0.0853, 0.7550],
        [0.2508, 0.7506, 0.6367, 0.8697]])
datatype of the tensor: torch.float32
shape of the tensor: torch.Size([3, 4])
device of the tensor: cpu


###MANIPULATING TENSORS###

In [33]:
#ADDITION
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [34]:
tensor *10

tensor([10, 20, 30])

In [35]:
tensor-10

tensor([-9, -8, -7])

In [36]:
#matrix multiplication
%%time
torch.matmul(tensor,tensor)


CPU times: user 936 µs, sys: 0 ns, total: 936 µs
Wall time: 927 µs


tensor(14)

In [37]:
#transpose of a tensor
tensor.T

<ipython-input-37-37774425ba5e>:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3571.)
  tensor.T


tensor([1, 2, 3])

In [38]:
tensor_1=torch.tensor(([1,2],
                      [3,4],
                      [5,6]))
tensor_1.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [39]:
#create a tensor between a range
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
#min
torch.min(x)

tensor(0)

In [41]:
#max
x.max()

tensor(90)

In [42]:
#mean or avg - it requires float dataype
torch.mean(x.type(torch.float32))

tensor(45.)

In [43]:
#sum
torch.sum(x)

tensor(450)

In [44]:
#finding the positional min and max
x.argmin()

tensor(0)

In [45]:
x.argmax()

tensor(9)

NUMPY && PYTORCH

In [46]:
#numPy array to tensor
import torch
import numpy as np

array=np.arange(2.3,4.2)
tensor=torch.from_numpy(array)
array,tensor

(array([2.3, 3.3]), tensor([2.3000, 3.3000], dtype=torch.float64))

In [47]:
#tensor to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))